name: "Muhammad Ifdhal Rumalutur"
description: "Greet someone"
author: "ifdhalrumalutur@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
